---
title: "Big Bird 1"
author: "Christian Endter"
date: "28/12/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

library(scales)

library(readxl)
library(lubridate)
library(janitor)
library(padr)
library(stringr)


`%!in%` = Negate(`%in%`)
`%+%` <- function(x,y) str_c(x,y)


```


```{r Import FAA}

data <- readRDS("KDEN FAA.RDS")

```


```{r Flight Data Import}
# Import Krishna's arrivals and departures
# N.B. The departures and arrivals empty columns are needed as this is faster than pivoting the final table
data_arrivals <- read.csv("Airline_Arrivals_Group.csv") %>% 
  rename(DATE=FL_DATE,TIME=ARR_TIME_BLK,ARRIVALS=Counts) %>% 
  mutate(AD = factor("A", levels=c("A","D")), DEPARTURES = 0)
data_departures <- read.csv("Airline_Departures_Group.csv") %>%
  rename(DATE=FL_DATE,TIME=DEP_TIME_BLK,DEPARTURES=Counts) %>% 
  mutate(AD = factor("D", levels=c("A","D")), ARRIVALS = 0)
data_flights <- rbind(data_arrivals,data_departures) %>%
  mutate(DATE = ymd(DATE), TOTAL = ARRIVALS + DEPARTURES)
rm(data_arrivals, data_departures)

# Convert time field to rounded hours for subsequent matching
data_flights$RTIME <- hour(ymd_hm(paste0(data_flights$DATE," ",substr(data_flights$TIME,1,4)))) 
data_flights$`AIRPORT ID` <- "KDEN"

data_flights <- data_flights %>%
  group_by(`AIRPORT ID`,DATE,RTIME) %>%
  summarise(ARRIVALS = sum(ARRIVALS), DEPARTURES = sum(DEPARTURES), TOTAL = sum(TOTAL))

# ~~~ !!! NOTE - NEED TO EVENTUALLY SCALE TO INCLUDE OTHER CIVILIAN FLIGHTS AND CARGO
```

# Import weather data
```{r Weather Data Import}
# Weather data post initial processing saved in RDS file with name "ICAO Weather.RDS"
data_weather <- readRDS("KDEN Weather.RDS")

```
# Import bird counts
```{r Bird Count Data Import}
# Note - currently only have daily data, so for now set RTIME to NA
data_birdcounts <- read.csv("birdCount_Aggregated.csv") %>% 
  dplyr::select(DATE = observationDate, COUNT = birdCount) %>%
  mutate(DATE = ymd(DATE), RTIME=NA) %>%
  mutate(`AIRPORT ID` = "KDEN")
```



```{r Data - Joining up the files}
## Assume we got clean input files
# Calculate TD, if we were to use that to match
# data <- mutate(data, TD = makeTD(RTIME))
# data_flights <- mutate(data_flights, TD = makeTD(RTIME))
# data_birdcounts <- mutate(data_birdcounts, TD = makeTD(RTIME))
# data_weather <- mutate(data_weather, TD = makeTD(RTIME))

## Merge 
# To ensure that we are not inadvertently losing records (days x time windows), start with empty data frame with all days in time period (maybe not the most elegant code to create empty master table, but it works:) A few notes to self:
#   rbind: need to create the unknown field for each day
#   date mutate: needed because of R POSIXct difficulty, otherwise different versions of date format, 
#   seemed fastest to do this crude work-around
#   summarise: needed to ensure grouped data frame collapses and join works on smaller df
empty <- tibble(DATE = seq(ymd("1992-01-01"),ymd("2019-01-01"), by= "days")) %>%
  pad("hour") %>% 
  mutate(RTIME = hour(DATE),`AIRPORT ID` = "KDEN") %>%
  dplyr::select(DATE,RTIME, `AIRPORT ID`) %>%
  mutate(DATE = ymd(substr(as.character(DATE),1,11))) 

# Used for TOD 
  # rbind(
  #   tibble(DATE = seq(ymd("1992-01-01"),ymd("2018-12-31"), by= "days")) %>%  
  #     mutate(RTIME = NA)) %>%
  # mutate(DATE = ymd(substr(as.character(DATE),1,11))) %>% 
  # dplyr::select(DATE,RTIME) %>% 
  # group_by(DATE, TD=makeTD(RTIME)) %>% 
  # summarise(n()) %>% 
  # dplyr::select(1:2) %>%
  # mutate(`AIRPORT ID` = "KDEN")


# Aggregate input tibbles to AIRPORT, DATE, TD level
# data_flights <- data_flights %>%
#   dplyr:: select(`AIRPORT ID`, DATE,TD,ARRIVALS, DEPARTURES, TOTAL) %>%
#   group_by(`AIRPORT ID`,DATE,TD) %>% 
#   summarise(ARRIVALS = sum(ARRIVALS), DEPARTURES = sum(DEPARTURES), TOTAL = sum(TOTAL))
# data_birdcounts <- data_birdcounts %>%
#   dplyr::select(`AIRPORT ID`,DATE,TD,COUNT) %>%
#   group_by(`AIRPORT ID`,DATE, TD) %>%
#   summarise(BIRDS = sum(COUNT))
# data_weather <- data_weather %>%
#   group_by(`AIRPORT ID`,DATE,TD) %>%
#   summarise_all(sum, na.rm=TRUE)
  
# Join the data against the master
# Note that we are gaining rows as we have RUNWAY, PRECIP, etc (even though documenation gives impression that only LHS rows used in left_join)
# should not gain rows on subsequent joins
master <- left_join(empty, data, by=c("AIRPORT ID" = "AIRPORT ID", "DATE"="DATE","RTIME"="RTIME"))

# Join the flights
master <- left_join(master,data_flights,by=c("AIRPORT ID" = "AIRPORT ID","DATE"="DATE","RTIME"="RTIME"))

# Join the birdcounts
master <- left_join(master,data_birdcounts, by=c("AIRPORT ID" = "AIRPORT ID","DATE"="DATE","RTIME"="RTIME"))

# Join the weather
master <- left_join(master,data_weather, by=c("AIRPORT ID" = "AIRPORT ID","DATE"="DATE","RTIME"="RTIME"))

# Replace NA with 0 for STRIKES
master <- mutate(master, STRIKE = replace_na(STRIKE,0))



############
saveRDS(master,"KDEN complete.RDS")
rm(data, data_birdcounts, data_flights, data_weather, empty, master)

##### NOTE - STRIKES WITHOUT TIME ARE TD=UNKNOWN AND HAVE NO FLIGHTS MATCHED AGAINST THEM, NEED TO DECIDE WHAT TO DO

## Calculate the probability of a strike ... WE SEEM TO LOSE SOME ROWS IN THIS AGGREGATION - SAME RUNWAY STRIKES?
# NOTE, CAN'T USE n() as it counts records and thus includes days with no strikes (=NA)
masterl <- master %>% 
  group_by(`AIRPORT ID`, DATE,TD, RUNWAY) %>%
  summarise(STRIKES = sum(STRIKE), TOTAL = sum(TOTAL), ARRIVALS = sum(ARRIVALS), DEPARTURES = sum(DEPARTURES),
            STRIKEP = STRIKES/TOTAL)

### TO CHECK ...~~~~~!!!!!!!!
# Note there are some FAA entries one dates/times which don't seem to have flights in the Krishna file, hence full join needed
#x <- full_join(data_flights,data, by=c("DATE" = "DATE", "RTIME"="RTIME")) 
```


# IGNORE FROM HERE ON DOWN,OLD CODE


# Import flight data - IGNORE POST KRISHNA'S NEW DATA
```{r Flight Data Import and Clean-up}

# Workflow flight import
# https://aspm.faa.gov/opsnet/sys/Airport.asp
# Output > Standard Report, MS Excel, no sub-totals
# Dates > Range 1/1/1992 to 1/1/2019
# Facilities > DEN
# Filters > No Filters
# Groupings > Date, Airport
# The resulting file still seems to be in some html format - so open in Excel, save as xlsx
# TODO - for other airports, check import range

data_flights <- read_xlsx("DEN 1992 - 2019.xlsx", range=("A8:K9871"))

# fix column names given source file has merged cells in header row
colnames(data_flights) <- c("DATE", "Facility","Carrier","Taxi","General","Military1","Total1","Civil", "Military2","Total2","GrandTotal")

# adjust count to take out military flights not reported in FAA strike database
data_flights <- data_flights %>% 
  mutate(TOTAL = GrandTotal - Military1 - Military2,
         `AIRPORT ID` = Facility,
         `AIRPORT ID` = as.factor(`AIRPORT ID`)) %>%
  dplyr::select(DATE,`AIRPORT ID`,TOTAL)

# adjust facility name
data_flights$`AIRPORT ID` <- paste0("K",data_flights$`AIRPORT ID`)

# fix dates (seems some months in serial format, others in actual date format)
data_flights$DATE <- coalesce(ydm(excel_numeric_to_date(as.numeric(data_flights$DATE))),
                              ymd(as.Date(data_flights$DATE,format="%m/%d/%Y")))

data_all %>% group_by(OPID) %>% summarise(count = n())

data %>% filter(is.na(TIME)) %>% nrow()
data %>% filter(is.na(TOD)) %>% nrow()

```



# Calculation of strike probability

```{r CALC daily strike risk}

# 1 For airport, for specific date, irrespective of ToD
# summarise by day, then join against those days which had flights (zero strikes = NA)
data_day <- data %>% group_by(DATE, `AIRPORT ID`) %>% 
  summarise(STRIKES = n()) %>% 
  ungroup() %>%
  right_join(data_flights,by=c("AIRPORT ID","DATE")) %>%
  mutate(RATIO = STRIKES / TOTAL * 100) %>%
  mutate(WEEK = week(DATE)) %>%
  right_join(data_weather, by=c("DATE")) %>%
  mutate(SKY = as.factor(replace_na(as.character(SKY),"UNKNOWN")))

# summarise by month and year - small multiples plot
x <-data_day %>% group_by(MONTH=month(DATE),YEAR=year(DATE)) %>% summarise(P=mean(RATIO,na.rm = TRUE)) %>% filter(YEAR > 1994)
ggplot(data=x,aes(x=MONTH,y=P)) + 
  geom_line() +
  facet_wrap(~YEAR)

```
# Are there distinct weekly differences across the year?
# yes - so need to look at this
```{r ANALYSIS - Weekly and day of year}

# Note
x <- data_day %>% group_by(WEEK) %>% summarise(P = mean(RATIO,na.rm=TRUE))
ggplot(data=x, aes(x=WEEK,y=P)) + geom_line() 

# weekly with distribution
ggplot(data=data_day%>% filter(RATIO<1), aes(x=WEEK,y=RATIO,group=WEEK)) + geom_boxplot() 

# day of year - not n() not helpful as it includes NAs
x <- data_day %>% group_by(DAY=yday(DATE)) %>% summarise(P = mean(RATIO,na.rm=TRUE), N=n()) 
ggplot(data=x, aes(x=DAY,y=P)) + geom_line()

```


```{r PREPARE for logistic regression}
# need to generate data set with columns P, Weights = No flights, WEEK, TOD, WEATHER
data_log <- data %>% group_by(DATE, `AIRPORT ID`, SKY, `PHASE OF FLT`) %>% 
  summarise(STRIKES = n()) %>% 
  ungroup() %>%
  right_join(data_flights,by=c("AIRPORT ID","DATE")) %>%
  mutate(RATIO = STRIKES / TOTAL * 100) %>%
  mutate(WEEK = as.factor(week(DATE))) %>%
  mutate(MONTH = as.factor(month(DATE))) %>%
  mutate(STRIKES = replace_na(STRIKES,0)) %>%
  mutate(STRIKEYN = if_else(STRIKES==0,0,1,1)) %>%
  filter(DATE > "1994-01-01") %>%
  left_join(data_weather, by=c("DATE")) %>%
  left_join(data_birdcounts, by=c("DATE")) %>%
  mutate(COUNT = replace_na(COUNT,0)) %>% 
  mutate(SKY = as.factor(replace_na(as.character(SKY),"UNKNOWN"))) %>%
  mutate(POF = as.factor(replace_na(as.character(`PHASE OF FLT`),"UNKNOWN"))) %>%
  mutate(POF = recode(POF,"Approach" = "APPROACH", "Arrival" = "ARRIVAL", "Climb" = "CLIMB", 
                      "Departure" = "DEPARTURE", "Landing roll" = "LANDING ROLL", 
                      "Landing Roll" = "LANDING ROLL", "Take-off run" = "TAKE-OFF RUN",
                      "Take-off Run" = "TAKE-OFF RUN", 
                      "Descent" = "DESCENT", "Taxi" = "TAXI", "Parked" = "PARKED"))

#PHASE OF FLIGHT, HEIGHT ---?
  mice(data1, m=1, maxit=500, method='cart', seed=500)
mod <- glm(RATIO ~ WEEK + AWND + POF, data=data_log, family=binomial(logit), weights=TOTAL)
mod <- glm(STRIKES ~ AWND + WEEK + COUNT, data=data_log, family=poisson)
mod <- glm(STRIKES ~ AWND + MONTH + COUNT, data=data_log, family=poisson)
mod <- hurdle(STRIKES ~ WEEK + AWND, data=data_log, dist="negbin")
mod <- zeroinfl(STRIKES ~ WEEK, data=data_log, dist="negbin")

modyn <- glm(STRIKEYN ~ WEEK + AWND + POF, data=data_log, family=binomial(link="logit"))

data_log$predict <- predict.glm(mod, newdata = data_log, type="response")
```


