---
title: "Big File Creation (the Jacobi way) for Krishna"
author: "Christian Endter"
date: "12/01/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(padr)

`%!in%` = Negate(`%in%`)
`%+%` <- function(x,y) str_c(x,y)
```

```{r Flight Data Import}
# Import Krishna's arrivals and departures
# N.B. The departures and arrivals empty columns are needed as this is faster than pivoting the final table
data_arrivals <- read.csv("Airline_Arrivals_Group.csv") %>% 
  rename(DATE=FL_DATE,TIME=ARR_TIME_BLK,ARRIVALS=Counts) %>% 
  mutate(AD = factor("A", levels=c("A","D")), DEPARTURES = 0)
data_departures <- read.csv("Airline_Departures_Group.csv") %>%
  rename(DATE=FL_DATE,TIME=DEP_TIME_BLK,DEPARTURES=Counts) %>% 
  mutate(AD = factor("D", levels=c("A","D")), ARRIVALS = 0)
data_flights <- rbind(data_arrivals,data_departures) %>%
  mutate(DATE = ymd(DATE), TOTAL = ARRIVALS + DEPARTURES)
rm(data_arrivals, data_departures)

# Convert time field to rounded hours for subsequent matching
data_flights$RTIME <- hour(ymd_hm(paste0(data_flights$DATE," ",substr(data_flights$TIME,1,4)))) 
data_flights$`AIRPORT ID` <- "KDEN"

data_flights <- data_flights %>%
  filter(DATE < "2019-01-01") %>%
  group_by(`AIRPORT ID`,DATE,RTIME) %>%
  summarise(ARRIVALS = sum(ARRIVALS), DEPARTURES = sum(DEPARTURES), TOTAL = sum(TOTAL))

# ~~~ !!! NOTE - NEED TO EVENTUALLY SCALE TO INCLUDE OTHER CIVILIAN FLIGHTS AND CARGO
```

# Import weather data
```{r Weather Data Import}
# Weather data post initial processing saved in RDS file with name "ICAO Weather.RDS"
data_weather <- readRDS("KDEN Weather.RDS")

```
# Import bird counts
```{r Bird Count Data Import}
# Note - currently only have daily data, so for now set RTIME to NA
data_birdcounts <- read.csv("birdCount_Aggregated.csv") %>% 
  dplyr::select(DATE = observationDate, COUNT = birdCount) %>%
  mutate(DATE = ymd(DATE), RTIME=NA) %>%
  mutate(`AIRPORT ID` = "KDEN")
```



```{r}
# The FAA data
data <- readRDS("KDEN FAA.RDS")

# modify the FAA data - take out non-essentials for smaller file
# aggregate to day and hour
d <- data %>% 
  dplyr::filter(!is.na(RTIME)) %>% 
  dplyr::select(-c(RUNWAY,PRECIP,SKY, TIME, LIGHT)) %>%
  group_by(DATE,RTIME) %>%
  summarise(STRIKES = sum(STRIKE))

# # there are several days/hours with more than one strike
# table(d$STRIKES)
# which(d$STRIKES==3)

# calculate flight numbers (non strikes) to replicate
# N.B.: Future -> use arrival/departure indicator to adjust those totals
# Note need to explicitly set NA to zero as otherwise subtraction screws up
df <- left_join(data_flights,d) %>%
  mutate(STRIKES = replace_na(STRIKES,0)) %>% 
  mutate(ATOTAL = TOTAL-STRIKES)

# # Check - was 128 total flights, now will be 125 and 3 strikes to be added
# dplyr::filter(df, DATE=="2008-07-20" & RTIME ==10)
# # Check - was 45 flights, now 44 non-struck, 1 with strike to be added
# dplyr::filter(df, DATE=="1998-05-08" & RTIME ==19)


# start with empty tibble with all possible days and hours
empty <- tibble(DATE = seq(ymd("1992-01-01"),ymd("2019-01-01"), by= "days")) %>%
  pad("hour") %>% 
  mutate(RTIME = hour(DATE),`AIRPORT ID` = "KDEN") %>%
  dplyr::select(DATE,RTIME, `AIRPORT ID`) %>%
  mutate(DATE = ymd(substr(as.character(DATE),1,11))) 

# map in the flights
m <- left_join(empty, df, by=c("AIRPORT ID" = "AIRPORT ID", "DATE"="DATE","RTIME"="RTIME"))
rm(empty, df)

# expand the file by number of total flights (could also do arrivals/departures separately)
# note, need to split into those days where we have flight info and where we don't ... of course there should be no strikes on those days without flight info but I'm too tired to deal with those errors/filter data down to only those days with flight info and strike
m <- mutate(m, ATOTAL = replace_na(ATOTAL,0))
m <- uncount(m,m$ATOTAL)


# # Check - was 128 total flights, now will be 125 and 3 strikes to be added
# dplyr::filter(m, DATE=="2008-07-20" & RTIME ==10)
# # Check - was 45 flights, now 44 non-struck, 1 with strike to be added
# dplyr::filter(m, DATE=="1998-05-08" & RTIME ==19)

n <- m
rm(m)

# go back to source data to keep individual lines for each strike (i.e. not aggregated by hour)
d <- data %>% 
  dplyr::filter(!is.na(RTIME)) %>% 
  dplyr::select(-c(RUNWAY,PRECIP,SKY, TIME, LIGHT))

# add the FAA data (can just add together as the master has all the empties)
n <- bind_rows(n,d) %>% arrange(DATE) %>% mutate(STRIKE = replace_na(STRIKE,0))

# map in the weather data
n <- left_join(n, data_weather, by=c("AIRPORT ID" = "AIRPORT ID", "DATE"="DATE","RTIME"="RTIME") )

# leaving out birdcounts as not by the hour 

# Check - was 128 total flights, now will be 125 and 3 strikes to be added
dplyr::filter(n, DATE=="2008-07-20" & RTIME ==10)
# Check - was 45 flights, now 44 non-struck, 1 with strike to be added
dplyr::filter(n, DATE=="1998-05-08" & RTIME ==19)

# !!!! outstanding, take out the number of lines for the strike
saveRDS(n, "BIG file the other way.RDS")

```

