---
title: "Data Creation_Day"
author: "Team Strikes"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
  code_folding: hide
  highlight: pygment
  theme: united
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(warn=-1)

```

```{r Check installed packages, echo = FALSE, warning=FALSE, message=FALSE}
# Creating a vector of packages used within
packages <- c(
  'dplyr',
  'lubridate',
  'magrittr',
  'tidyverse',
  'readxl',
  'zoo'
)

# Checking for package installations on the system and installing if not found
if (length(setdiff(packages, rownames(installed.packages()))) > 0) {
  install.packages(setdiff(packages, rownames(installed.packages())))  
}

# Including the packages for use
for(package in packages){
  library(package, character.only = TRUE)
}

```

#Loading & Saving Source Files 

```{r Weather File Load}
###### Uncomment to run for the airport required 

#weather <- read_csv("DFW/w_DFW.csv") #this doesn't need the precip code 
#weather <- read_csv("ORD/w_ORD.csv") 
#weather <- read_csv("SMF/w_SMF.csv") 
#weather <- read_xls("KDEN/w_DEN.xls") 

#converts the date column into date (for non KDEN)
# weather<- weather %>%
#   dplyr::rename(DATE = YEARMODA)

#convert to Date 
weather$DATE <- ymd(weather$DATE)

#corrects the precip Column
 weather <- weather %>%
   mutate(PRCP = substr(PRCP, 1, 4))

#converts all of the columns to numeric up until precip
weather[2:11] <- sapply(weather[2:11], as.numeric, 
                        na.rm= TRUE)
#converts all the columns to factor for the remaining column 
weather[11:17] <- lapply(weather[12:16], factor)


sapply(weather,class)

weather<- weather %>% 
  select(-GUST, -STP)

weather <- weather[complete.cases(weather), ]
weather <-
  weather[!(weather$MXSPD == 999.9 |
                 weather$PRCP == 99.99), ]

#NA Value Check
colSums(is.na(weather))

#weather %>% filter(is.na(weather$TEMP))

###### Uncomment to run for the airport required -SAVE
#saveRDS(weather,"DFW/DFW_Weather.RDS") 
#saveRDS(weather,"ORD/ORD_Weather.RDS")
#saveRDS(weather,"SMF/SMF_Weather.RDS")
#saveRDS(weather,"KDEN/KDEN_Weather.RDS")


```

```{r Birdcount Load }

###### Uncomment to run for the airport required 

# birdcount <- read_csv("DFW/birdCount_Aggregated_DFW.csv")
 birdcount <- read_csv("ORD/birdCount_Aggregated_ORD.csv")
# birdcount <- read_csv("SMF/birdCount_Aggregated_SMF.csv")


#--- update 3/28 removed all of them from the import -tk
    #birdcount <- birdcount %>% filter(milesFromAirport < 10) 
#Correct the names of the file 
names(birdcount)<-c("DATE","BIRDCOUNT")

#convert to date format 
birdcount$DATE <- as.Date(birdcount$DATE, format = "%m/%d/%y")

#already grouped by day
# birdcount <-
#   birdcount %>% group_by(DATE) %>% summarise(BIRDCOUNT = sum(howMany))

birdcount$BIRDCOUNT[is.na(birdcount$BIRDCOUNT)] <- 0

#checking class 
sapply(birdcount,class)

#NA Value Check
#colSums(is.na(birdcount))
#birdcount %>% filter(is.na(weather$TEMP))


###### Uncomment to run for the airport required -SAVE
# saveRDS(birdcount,"DFW/DFW_BirdCount.RDS")
 saveRDS(birdcount,"ORD/ORD_BirdCount.RDS")
# saveRDS(birdcount,"SMF/SMF_BirdCount.RDS")

```

```{r Strikes Load}

#all strikes are till december 2019
# faa <- read_xlsx("DFW/DFW strikes.xlsx")
# faa <- read_xlsx("ORD/ORD strikes.xlsx")
# faa <- read_xlsx("SMF/SMF strikes.xlsx")
# faa <- read_xlsx("KDEN/KDEN strikes.xlsx")

#Assigns the binary value of 1 to the Strie 
faa['STRIKE'] <- 1

#Applies the Height to 0 if it is not there
#faa$HEIGHT[is.na(faa$HEIGHT)] <- 0 #6338 

#Applies the 2000 Filter of feet to the height (Removes anything above )
faa <- faa %>% filter(HEIGHT <= 2000)

#Converts the data format 
faa$INCIDENT_DATE <- as.Date(faa$INCIDENT_DATE, '%Y-%m-%d')


#Only maintains the Date and totals the number of strikes by Day
faa <- faa %>% 
  group_by(INCIDENT_DATE, STRIKE) %>% 
  summarise(STRIKECOUNT = sum(STRIKE)) %>% 
  filter(INCIDENT_DATE >= as.Date("2000-01-01"))

faa <-  faa %>% 
  dplyr::rename(DATE = INCIDENT_DATE) 
  
head(faa)
tail(faa)

sum(faa$STRIKE)
sum(faa$STRIKECOUNT)

#checks class
sapply(faa,class)

#NA Value Check
colSums(is.na(faa))
#faa %>% filter(is.na(faa$))

### Save the file
# saveRDS(faa,"DFW/DFW_FAA.RDS")
# saveRDS(faa,"ORD/ORD_FAA.RDS")
# saveRDS(faa,"SMF/SMF_FAA.RDS")
# saveRDS(faa,"KDEN/KDEN_FAA.RDS")


```


```{r Flight Load}
# Import Krishna's arrivals and departures
# N.B. The departures and arrivals empty columns are needed as this is faster than pivoting the final table
 
# data_arrivals <- read.csv("DFW/Airline_Arrivals_Group_DFW.csv") %>%
#   rename(DATE=FL_DATE,TIME=ARR_TIME_BLK,ARRIVALS=Counts) %>%
#   mutate(AD = factor("A", levels=c("A","D")), DEPARTURES = 0)
# 
# data_departures <- read.csv("DFW/Airline_Departures_Group_DFW.csv") %>%
#   rename(DATE=FL_DATE,TIME=DEP_TIME_BLK,DEPARTURES=Counts) %>%
#   mutate(AD = factor("D", levels=c("A","D")), ARRIVALS = 0)


# data_arrivals <- read.csv("ORD/Airline_Arrivals_Group_ORD.csv") %>%
#   rename(DATE=FL_DATE,TIME=ARR_TIME_BLK,ARRIVALS=Counts) %>%
#   mutate(AD = factor("A", levels=c("A","D")), DEPARTURES = 0)
# 
# data_departures <- read.csv("ORD/Airline_Departures_Group_ORD.csv") %>%
#   rename(DATE=FL_DATE,TIME=DEP_TIME_BLK,DEPARTURES=Counts) %>%
#   mutate(AD = factor("D", levels=c("A","D")), ARRIVALS = 0)

data_arrivals <- read.csv("SMF/SMF_Arrivals_Group.csv") %>%
  rename(DATE=FL_DATE,TIME=ARR_TIME_BLK,ARRIVALS=Counts) %>%
  mutate(AD = factor("A", levels=c("A","D")), DEPARTURES = 0)
data_departures <- read.csv("SMF/SMF_Departures_Group.csv") %>%
  rename(DATE=FL_DATE,TIME=DEP_TIME_BLK,DEPARTURES=Counts) %>%
  mutate(AD = factor("D", levels=c("A","D")), ARRIVALS = 0)


#NEVER TO BE RUN AGAIN 
# data_arrivals <- read.csv("KDEN/Airline_Arrivals_Group.csv") %>%
#   rename(DATE=FL_DATE,TIME=ARR_TIME_BLK,ARRIVALS=Counts) %>%
#   mutate(AD = factor("A", levels=c("A","D")), DEPARTURES = 0)
# 
# data_departures <- read.csv("KDEN/Airline_Departures_Group.csv") %>%
#   rename(DATE=FL_DATE,TIME=DEP_TIME_BLK,DEPARTURES=Counts) %>%
#   mutate(AD = factor("D", levels=c("A","D")), ARRIVALS = 0)



####
data_flights <- rbind(data_arrivals,data_departures) 

data_flights$DATE <- ymd(data_flights$DATE)

data_flights <- data_flights %>% 
  select(-AD) %>% 
  dplyr::group_by(DATE) %>% 
  summarise(TOTAL = sum(ARRIVALS,DEPARTURES))
rm(data_arrivals, data_departures)


# ##never to be run AGAIN
# kden <- readRDS("SMF/SMF_FINAL.RDS")
# kden <-
#   left_join(kden, data_flights , by = c("DATE" = "DATE"))
# kden$TOTAL.x <- ifelse(is.na(kden$TOTAL.x), kden$TOTAL.y, kden$TOTAL.x)
# kden<-kden %>%
#   rename(TOTAL = TOTAL.x) %>% dplyr::select(-c(TOTAL.y))
#  saveRDS(kden,"SMF/SMF_FINAL.RDS")

# saveRDS(data_flights,"DFW/DFW_Flights.RDS")
# saveRDS(data_flights,"ORD/ORD_Flights.RDS")
# saveRDS(data_flights,"SMF/SMF_Flights.RDS")
 
```

#Master File Creation

```{r Load RDS }
### Note - assumes these have been cleaned already and  contain a DATE and RTIME field

# data_w <- readRDS("DFW/DFW_Weather.RDS")
# data_f <- readRDS("DFW/DFW_Flights.RDS")
# data_b <- readRDS("DFW/DFW_BirdCount.RDS")
# data_faa <- readRDS("DFW/DFW_FAA.RDS")

# data_w <- readRDS("ORD/ORD_Weather.RDS")
# data_f <- readRDS("ORD/ORD_Flights.RDS")
# data_b <- readRDS("ORD/ORD_BirdCount.RDS")
# data_faa <- readRDS("ORD/ORD_FAA.RDS")

# data_w <- readRDS("SMF/SMF_Weather.RDS")
# data_f <- readRDS("SMF/SMF_Flights.RDS")
# data_b <- readRDS("SMF/SMF_BirdCount.RDS")
# data_faa <- readRDS("SMF/SMF_FAA.RDS")

# data_w <- readRDS("KDEN/KDEN_Weather.RDS")
# data_f <- readRDS("KDEN/KDEN flights.RDS")
# data_b <- readRDS("KDEN/KDEN_BirdCount.RDS")
# data_faa <- readRDS("KDEN/KDEN_FAA.RDS")


```

```{r}
strikes <- tibble(DATE = seq(ymd("2000-01-01"),ymd("2019-12-31"), by= "days")) 

```

```{r}

data_b <- data_b %>%
  group_by(DATE) %>%
  summarise(BIRDCOUNT = sum(BIRDCOUNT))

strikes <-
  left_join(strikes, data_b , by = c("DATE" = "DATE"))

```

```{r}
data_f <- data_f %>%
  group_by(DATE) %>%
  summarise(TOTAL = sum(TOTAL))

strikes <-
  left_join(strikes, data_f , by = c("DATE" = "DATE"))


```

```{r}
strikes <-
  left_join(strikes, data_w , by = c("DATE" = "DATE"))
```

```{r}
strikes <-
  left_join(strikes, data_faa, by = c("DATE" = "DATE"))
```

```{r}
strikes <- cbind(
  strikes,
  data.frame(
    YEAR = as.factor(format(strikes$DATE, format = "%Y")),
    MONTH = as.factor(format(strikes$DATE, format = "%m")),
    DAYOFWEEK = as.factor(format(strikes$DATE, format = "%A")),
    SEASON = as.factor(factor(
      format(as.yearqtr(
        as.yearmon(strikes$DATE, "%m/%d/%Y") + 1 / 12
      ), "%q"),
      levels = 1:4,
      labels = c("winter", "spring", "summer", "fall")
    ))
  )
)

strikes$STRIKE[is.na(strikes$STRIKE)] <- 0
  
strikes$STRIKECOUNT[is.na(strikes$STRIKECOUNT)] <- 0

strikes$BIRDCOUNT[is.na(strikes$BIRDCOUNT)] <- 0


```


```{r KDEN Code }
# Check for NAs in all columns
colSums(is.na(KDEN))

#saveRDS(strikes,"DFW/DFW_FINAL.RDS")
#saveRDS(strikes,"ORD/ORD_FINAL.RDS")
#saveRDS(strikes,"SMF/SMF_FINAL.RDS")
#saveRDS(strikes,"KDEN/KDEN_FINAL.RDS")

```


```{r}

```

```{r}
ratio_f<- function(master.data) {
  
  master.data <- master.data[complete.cases(master.data), ]

  master.data <- master.data %>%
  mutate(
    WEEK = lubridate::week(master.data$DATE),
    YEAR = lubridate::year(master.data$DATE)
  ) %>%
  mutate(RATIO = STRIKECOUNT / TOTAL * 10000)
t.data <- master.data %>%
  mutate(RATIO = STRIKECOUNT / TOTAL * 10000) %>%
  group_by(YEAR, WEEK) %>%
  summarise(RATIO = mean(RATIO)) %>%
  mutate(RISK = .bincode(
    RATIO,
    breaks = quantile(RATIO, probs = seq(0, 1, 1 / 3)),
    include.lowest = TRUE
  ) - 1)
t.data <- t.data %>%
  group_by(YEAR, WEEK) %>%
  summarise(RATIOP = mean(RATIO)) %>%
  mutate(RISK = .bincode(
    RATIOP,
    breaks = c(0, min(RATIOP) + (1:2) * (max(RATIOP) - min(RATIOP)) / 3, max(RATIOP)),
    include.lowest = TRUE
  ) - 1)
master.data <-
  left_join(master.data, t.data, by = c("YEAR" = "YEAR", "WEEK" = "WEEK"))
master.data$RISK <-
  as.factor(ifelse(master.data$RISK == 0, "L", ifelse(master.data$RISK == 1, "M", "H")))
return(master.data)
}


### Merging all the airfields 
SMF <- readRDS("SMF/SMF_FINAL.RDS")
ORD <- readRDS("ORD/ORD_FINAL.RDS")
DFW <- readRDS("DFW/DFW_FINAL.RDS")
KDEN <- readRDS("KDEN/KDEN_FINAL.RDS")

#Adding the Airport ID for KDEN
SMF$`AIRPORT ID` <- "KSMF"
ORD$`AIRPORT ID` <- "KORD"
DFW$`AIRPORT ID` <- "KDFW"
KDEN$`AIRPORT ID` <- "KDEN"

#Adding the ratios 
SMF<-ratio_f(SMF)
ORD<-ratio_f(ORD)
DFW<-ratio_f(DFW)
KDEN<-ratio_f(KDEN)

#Binding the airports (all but KDEN)
master.data<- rbind(SMF,ORD)
master.data<- rbind(master.data,DFW)

#Removing Tornedo Funnel Cloud information since it was not relevant
master.data <- 
  master.data %>% 
  select(-TORNADO_FUNNELCLOUD,-SNOW_ICE.1)

#Ensuring the order and names of the columns are the same
KDEN<-KDEN %>% 
  select(DATE, BIRDCOUNT, TOTAL, TEMP, DEWP, SLP, VISIB, WDSP, MXSPD, PRCP, FOG, RAIN_DRIZZLE, SNOW_ICE, HAIL, THUNDER, STRIKE, STRIKECOUNT, YEAR, MONTH, DAYOFWEEK, SEASON, `AIRPORT ID`, WEEK, RATIO, RATIOP, RISK)

#Binding KDEN
master.data <- rbind(master.data,KDEN)

#Code to remove any NAs
master.data <- master.data[complete.cases(master.data), ]

master.data <- master.data %>% rename(FLIGHTCOUNT = TOTAL)

#Code to create Ratios

master.data %>% group_by(`AIRPORT ID`) %>% 
  summarise(count = sum(STRIKECOUNT))
```


```{r}

#Save the Master Data 
saveRDS(master.data,"AIRFIELDS_MASTERv2.RDS")

#write to CSV
write.csv(master.data,"AIRFIELDS_MASTER_v2.csv")
data<-readRDS("AIRFIELDS_MASTER.RDS")

data %>% filter(is.na(data))


View(data)

colSums(is.na(data))

View(KDEN_FAA)

View(`KDEN flights`)



```
